import jsPDF from "jspdf";

interface Recipe {
  name: string;
  ingredients: string[];
  instructions: string[];
  cookingTime?: string;
  servings?: string;
  difficulty?: string;
}

export const generateRecipePdf = (recipe: Recipe) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const maxWidth = pageWidth - margin * 2;
  let yPosition = 20;

  // Title
  doc.setFontSize(24);
  doc.setFont("helvetica", "bold");
  const titleLines = doc.splitTextToSize(recipe.name, maxWidth);
  doc.text(titleLines, margin, yPosition);
  yPosition += titleLines.length * 10 + 5;

  // Meta info
  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  const metaInfo: string[] = [];
  if (recipe.cookingTime) metaInfo.push(`Time: ${recipe.cookingTime}`);
  if (recipe.servings) metaInfo.push(`Servings: ${recipe.servings}`);
  if (recipe.difficulty) metaInfo.push(`Difficulty: ${recipe.difficulty}`);
  
  if (metaInfo.length > 0) {
    doc.text(metaInfo.join("  |  "), margin, yPosition);
    yPosition += 10;
  }

  // Divider
  yPosition += 5;
  doc.setDrawColor(200, 200, 200);
  doc.line(margin, yPosition, pageWidth - margin, yPosition);
  yPosition += 15;

  // Ingredients section
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.text("Ingredients", margin, yPosition);
  yPosition += 10;

  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  recipe.ingredients.forEach((ingredient) => {
    if (yPosition > 270) {
      doc.addPage();
      yPosition = 20;
    }
    const lines = doc.splitTextToSize(`• ${ingredient}`, maxWidth);
    doc.text(lines, margin, yPosition);
    yPosition += lines.length * 6 + 2;
  });

  yPosition += 10;

  // Instructions section
  if (yPosition > 250) {
    doc.addPage();
    yPosition = 20;
  }

  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.text("Instructions", margin, yPosition);
  yPosition += 10;

  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  recipe.instructions.forEach((instruction, index) => {
    if (yPosition > 270) {
      doc.addPage();
      yPosition = 20;
    }
    const lines = doc.splitTextToSize(`${index + 1}. ${instruction}`, maxWidth);
    doc.text(lines, margin, yPosition);
    yPosition += lines.length * 6 + 4;
  });

  // Footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(9);
    doc.setTextColor(150);
    doc.text(
      `Generated by PantryMate`,
      margin,
      doc.internal.pageSize.getHeight() - 10
    );
    doc.text(
      `Page ${i} of ${pageCount}`,
      pageWidth - margin - 20,
      doc.internal.pageSize.getHeight() - 10
    );
  }

  // Download
  const fileName = recipe.name.toLowerCase().replace(/\s+/g, "-") + ".pdf";
  doc.save(fileName);
};
